version: "3.5"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: masterrecipe-backend
    hostname: backend
    image: masterrecipe-backend
    ports:
      - "${MASTERRECIPE_BACKEND_PORT:-8000}:${MASTERRECIPE_BACKEND_PORT:-8000}"
    env_file:
      - ./backend/core/.env
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: masterrecipe-frontend
    hostname: frontend
    image: masterrecipe-frontend
    ports:
      - "${MASTERRECIPE_FRONTEND_PORT:-3000}:${MASTERRECIPE_FRONTEND_PORT:-3000}"
    env_file:
      - ./frontend/.env
  db:
    image: postgres:15.3-alpine
    container_name: masterrecipe-db
    hostname: db
    ports:
      - 5432:5432
    env_file:
      - ./backend/core/.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
